spring.application.name=MagicApi

# Conexión a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mtg
spring.datasource.username=root
spring.datasource.password=Abc123.
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true

